### ISSUE TITLE
about release the model

### ISSUE THREAD

**Issue by wmh02240** [Soltanilara/DNS#2]
Hi, Thank you for your excellent work, I am very interested in this project. Is there a plan to open source the pre-trained model?

**Comment by aghafourian** [comment]
Hello, thanks for your interest. Sure I can also upload the pre-trained model soon. Please feel free to check back.

**Comment by wmh02240** [comment]
Okay，Thanks!

**Comment by aghafourian** [comment]
@wmh02240 The pre-trained model is now available for download.
